version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/create_test_db.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 20
