package common

const (
	MONGO_DB_ERROR             = "MONGO_DB_ERROR"
	INVALID_REQUEST_BODY       = "INVALID_REQUEST_BODY"
	INVALID_PARAM              = "INVALID_PARAM"
	UNAUTHORIZED               = "UNAUTHORIZED"
	EMAIL_ALREADY_EXISTS       = "EMAIL_ALREADY_EXISTS"
	USERNAME_ALREADY_EXISTS    = "USERNAME_ALREADY_EXISTS"
	USER_NOT_FOUND             = "USER_NOT_FOUND"
	INCORRECT_PASSWORD         = "INCORRECT_PASSWORD"
	COMMUNITY_NOT_FOUND        = "COMMUNITY_NOT_FOUND"
	COMMUNITY_ALREADY_EXISTS   = "COMMUNITY_ALREADY_EXISTS"
	POST_NOT_FOUND             = "POST_NOT_FOUND"
	COMMENT_NOT_FOUND          = "COMMENT_NOT_FOUND"
	INVALID_CREDENTIALS        = "INVALID_CREDENTIALS"
	FORBIDDEN                  = "FORBIDDEN"
)
